LDLIBS := $(shell pkg-config --libs opencv4)
CXXFLAGS := $(shell pkg-config --cflags opencv4 eigen3)
CXXFLAGS += -g -Wall -Wextra -MMD

PREFIX := /usr/local

fix-perspective: intersect-lines-2d.o fix-perspective.cpp

install: fix-perspective
	install $< $(PREFIX)/bin

check:
	pkg-config --print-errors opencv4 eigen3

clean:
	$(RM) *.o *.d fix-perspective

deps-ubuntu:
	apt-get --no-install-recommends install pkg-config g++ libeigen3-dev libopencv-dev # needs OpenCV 4

help:
	@echo "Targets"
	@echo
	@echo "  deps-ubuntu	Install system dependencies (may need su)"
	@echo "  check		Verify that all system dependencies are present"
	@echo "  install	Build fix-perspective and install into PREFIX/bin"
	@echo "  clean		Remove all files generated by previous builds"
	@echo
	@echo "Variables"
	@echo
	@echo "  PREFIX		Path where to install the program into [$(PREFIX)]"

.PHONY: check clean deps-ubuntu help install 

-include $(wildcard *.d)
